DEFAULT_FIGHTS_FILE_NAME = "raw_total_fight_data.csv"
DEFAULT_FIGHTERS_FILE_NAME = "datasets_255092_536001_raw_fighter_details.csv"

DEFAULT_PRIOR_WINS = 4
DEFAULT_PRIOR_LOSSES = 4
DEFAULT_PRIOR_TIES = 0
